version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5439:5432"  # Cambiado a 5439 para que coincida con DB_PORT en .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Añadido para definir el usuario de la BD
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /var/lib/pgadmin
  #   depends_on:
  #     - db